<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AllMiniLmL6V2Sharp" Version="0.0.3" />
    <PackageReference Include="LangChain.Providers.OpenAI" Version="0.17.0" />
    <PackageReference Include="LangChain.Splitters.CSharp" Version="0.17.1" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.Analysis" Version="0.23.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.10.0" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.AutoML" Version="0.23.0" />
    <PackageReference Include="Microsoft.ML.Mkl.Components" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="Microsoft.ML.Parquet" Version="0.23.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.1" />
    <PackageReference Include="Neo4j.Driver" Version="6.3.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.30" />
    <PackageReference Include="Qdrant.Client" Version="1.19.0" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.12" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.12" />
  </ItemGroup>

</Project>
